name: Release dev container templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Publish templates to ghcr.io
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"
          oci-registry: ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
